In [1]:
import numpy as np #importing numpy with alias np

# What is the Difference Between Numpy array and Matrix and a Vector?

> array is n-dims, matrix is 2-dim, vector is 1-dim

In [7]:
mylist = [1, 2, 3]
n = np.array(mylist)
type(n)

numpy.ndarray

#Creating Multi-Dimensional Array

In [12]:
npMatrix = np.matrix([[1,2,3], [4,5,6],[7,8,9]])
npNdArray = np.array([[1,2,3], [4,5,6],[7,8,9]])

## Get the dimensions of ndarray

In [15]:
npMatrix.shape

(3, 3)

## Generating a Sequence with arange

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2) #generating numbers from 0 to 10 in an interval of 2

array([0, 2, 4, 6, 8])

## Generating Zeros and Ones

In [29]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Changing Dimensions of a ndArray using reshape

In [32]:
mn = np.arange(0, 50, 2)

In [35]:
mn.reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [37]:
o = np.linspace(0, 7, 10) 
# return 10 evenly spaced values from 0 to 7, 
#NB: it usaully gives output in decimals unlike the arange function

In [39]:
o.resize(5,2)
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

##what is the difference between resize and reshape?

> The reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.

#Generating Random Values

In [40]:
np.random.rand(3,3) #Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

array([[0.54886093, 0.16803097, 0.61191111],
       [0.94786177, 0.83983713, 0.3082617 ],
       [0.56486516, 0.29110361, 0.89668123]])

In [43]:
np.random.randn(3,3) #Return a samples from the “standard normal” Z-distribution.

array([[ 1.66795608,  0.19454352, -0.05565042],
       [-0.54842994,  1.20348379,  0.70492375],
       [ 0.89114731, -1.33714445, -0.43764482]])

In [44]:
np.random.randint(4,15,10) #Return random integers from low (inclusive) to high (exclusive).

array([ 5,  7, 14, 14, 11,  7,  8, 14, 12,  5])

In [45]:
np.random.randint(0, 10, (4,3)) #with desired shape

array([[0, 1, 3],
       [2, 5, 0],
       [0, 2, 9],
       [8, 8, 2]])

#Indexing

In [47]:
indexArray= np.random.randint(4,15,10)

In [49]:
indexArray[-1] #regular python Indexing and slicing works with numpy arrays too

9

In [50]:
indexArray[:-2]

array([14, 12,  9, 14, 10,  5,  6, 14])

In [54]:
mm=np.arange(36).reshape(6,6)

In [55]:
mm[4, 2:5] #use : to select a range of rows or columns

array([26, 27, 28])

In [58]:
mm[3::,3:]

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [59]:
mm[mm > 25] #conditional indexing

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [61]:
mm[mm > 25]=25  #changing all the values that are greater than 25 to 25
mm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [62]:
mm[1:,4] # Rows Greater than 0 and 4 th column

array([10, 16, 22, 25, 25])

#Testing

In [75]:
import numpy as np
array1 = np.arange(15,40)
array2 = np.arange(10,25)
even_aaray1 = np.arange(2,20,2)
even_aaray2 = np.arange(34,42,2)
stacked = np.stack((np.arange(2,20,2), np.arange(2,20,2)))
eleAtThreeTwo=np.arange(36).reshape(6,6)[2,1]
zMat=np.random.randn(5,2)
eleLast=zMat[-1,-1]
print(zMat,end="\n\n\n")
print(f'Min : {np.min(zMat)}')
print(f'Max : {np.max(zMat)}')
print(f'Std : {np.std(zMat)}')
print(f'Std : {np.var(zMat)}')
print(f'Mean : {np.mean(zMat)}')

[[ 1.49619534 -0.97692409]
 [-0.12610885 -0.77937759]
 [ 0.70774879  0.2345681 ]
 [ 2.78074432  0.18250318]
 [-1.52828241  0.76217656]]


Min : -1.5282824146220642
Max : 2.780744315613188
Std : 1.1956845857723708
Std : 1.4296616286536459
Mean : 0.27532433436672255
